# Generated by Django 4.0.5 on 2022-06-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_treino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='Aluno',
            new_name='aluno',
        ),
    ]
