# Generated by Django 4.0.5 on 2022-06-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_rename_aluno_treino_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.treino')),
            ],
        ),
    ]
